### ISSUE TITLE
after building the ctf docker image running it results in an error

### ISSUE THREAD

**Issue by Lunarequest** [LiveOverflow/pwn_docker_example#1]
i built the docker image for ctf but on running this command 
```
sudo docker run --rm -v $PWD:/pwd --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d --name ctf -i ctf:ubuntu19.1
```
i get this error
```
Unable to find image 'ctf:ubuntu19.1' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/ctf/manifests/ubuntu19.1: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fctf%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

have i done something wrong or is there an issue i with the script.

on manjaro kyria 19.0.1

**Comment by stgrmks** [comment]
Sounds like an issue with your internet/vpn connection. See https://github.com/docker/for-win/issues/611 for further details.

**Comment by Lunarequest** [comment]
Acctully I am running this on manjaro a linux distro. I was able to build the image prior to this command and trying to build the image in the ctf folder basically results in docker saying its already built.

**Comment by Idleless** [comment]
The command should be 
`sudo docker run --rm -v $PWD:/pwd --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -d --name ctf -i ctf:ubuntu19.10`

The '0' at the end is cut off in the ctf dockerfile comment.

**Comment by Lunarequest** [comment]
yeah @Idleless `s solution worked
